---
deployment:
  tasks:
    - export DEPLOYPATH=/home/globalallianc/site/
    - echo "Starting deployment without build process..."
    - /bin/cp -r .next/standalone/* $DEPLOYPATH
    - /bin/cp -r .next/static $DEPLOYPATH.next/
    - /bin/cp -r public $DEPLOYPATH
    - /bin/cp package-deploy.json $DEPLOYPATH/package.json
    - chmod +x $DEPLOYPATH/server.js
    - chmod 644 $DEPLOYPATH/package.json
    - chmod -R 755 $DEPLOYPATH.next/
    - echo "Deployment completed successfully!"
