import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import TopBarServer from "@/components/TopBarServer";
import HeaderServer from "@/components/HeaderServer";

export const dynamic = "force-dynamic";
export const fetchCache = "force-no-store";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <TopBarServer />
        <HeaderServer />
        {children}
      </body>
    </html>
  );
}
